services:
  backend:
    build: 
      context: ./backend
    container_name: backend_uvicorn_server
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  frontend:
    restart: always
    build: 
      context: ./frontend/my-app-mobile
    container_name: frontend_server
    ports:
      - "8081 : 8081"

  db:
    # Restart the postgreSQL server if it shuts down 
    restart: always
    image: postgres:latest
    container_name: postgres_db
    # Default shared memory of Docker containers is usually too small for the db
    shm_size: 1GB
    ports:
      - "5432 : 5432"
    volumes:
      # Ensure data is not lost on container restart
      - postgres_data: /var/lib/postgresql

    # These variables are injected when initializing the database below
    # Enable SCRAM-SHA-256 authentication on both local and remote hosts
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_SQL_KEY}
      - POSTGRES_DB=mydb
      - POSTGRES_INITDB_ARGS=--auth-local=scram-sha-256 --auth-host=scram-sha-256
  
    deploy:
      ressources:
        limits:
          cpus: "6.0"
          memory: "4GB"
    
    healthcheck:
      # Check the readiness of the db
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

    # Load pg_stat_statements on server startup for query optimization (It must be included in the queries as well)
    # Autovacumm cleans up after deletions or updates
    command: >  
      postgres
        -c shared_preload_libraries='pg_stat_statements'
        -c autovacuum=on
        -c max_connections=200
        -c shared_buffers='1GB'
        -c effective_cache_size='3GB'
        -c maintenance_work_mem='256MB'
        -c checkpoint_completion_target=0.9
        -c wal_buffers='16MB'
        -c default_statistics_target=100
        -c random_page_cost=1.1
        -c effective_io_concurrency=200
        -c work_mem='5242kB'
        -c min_wal_size='1GB'
        -c max_wal_size='4GB'
        -c huge_pages='off'
        -c max_worker_processes=6
        -c max_parallel_workers=6
        -c max_parallel_maintenance_workers=3
        -c max_parallel_workers_per_gather=3

volumes:
  postgres_data: