
"""
    Used to test the logic behind taking the streamed NLP response and performing TTS. One option would be to take each chunk generated by the NLP and performing emotion
    detection, TTS conversion and artkit coefficient conversion. However, this would most likely lead to significant lack of context. Hence, multiple chunks should be 
    concatenated and post-processed. This could be done by identifying punctuation marks and splitting the LLM output into sentences. But when sentences are too small 
    (maybe even one or two words), lack of context still would occur. Thus, we concatenate a list of chunks based on two conditions:
    1) the list contains at least a given number of chunks (for example 10)
    2) the last chunk contains an punctuation mark (potentially check through regex)

"""

import os
import requests
import traceback

url = "http://localhost:8000/response/stream"
BASE_DIR = os.path.dirname(os.path.abspath(__file__)) 
path = os.path.join(BASE_DIR, "../../data/testing/streamingNLP.txt")
os.makedirs(os.path.dirname(path), exist_ok = True)
input = {
    "input" : [{
        "role": "user",
        "content": "hello"
    }],
    "interview_type" : 1
}

with requests.post(url, stream=True, json = input) as r:
    try:
        count = 0
        partial_text = ""
        for chunk in r.iter_content(decode_unicode = True, chunk_size = 1024):
            partial_text += chunk
            count = count + 1
            print(chunk, end='', flush=True)

            if count >= 10 and chunk.strip() in ["!", ".", ":", ";"]:
                print(partial_text)     # replace with post-processing pipeline
                partial_text = ""
                count = 0
    except Exception as e:
        traceback.print_exc()