from funasr import AutoModel
import os
import numpy as np
from dotenv import load_dotenv
import torch
import logging

_models = {}        # Avoid time consuming model reloading
device = "cuda" if torch.cuda.is_available() else "cpu"
load_dotenv()
HF_TOKEN = os.environ["HF_TOKEN"]

# Configure basic logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

logger = logging.getLogger(__name__)


def load_model(model_id : str):
    """ Load model with ID given with GPU acceleration if possible

    Args:
        model_id (str): ID of the ML model provided
    """
    if model_id not in _models.keys():
        _models[model_id] = AutoModel(
            model = model_id,
            hub = "hf", 
            device = device,
            disable_update = True,      # Skip updates of funasr models
        )

def emotion_detection(
        audio : bytes, 
        language : str,
        model_id : str = ["iic/emotion2vec_plus_seed", "iic/emotion2vec_plus_base", "iic/emotion2vec_plus_large"],
    ) -> np.ndarray:
    """ Generate scores for each of the following emotions using emotion2vec in the same order : angry, disgusted, fearful, happy,
    neutral, other, sad, surprised, unk

    Args:
        audio (bytes): raw binary audio bytes to be processed by the model
        model_id (str): ID of the emotion2vec model to sue
        language (str) : language code to reduce latency

    Returns:
        ndarray : numpy array with the output scores
    """
    if model_id in _models.keys():
        model = _models[model_id]
    else:
        logger.info(msg = "Model not loaded")

    try:
        result =  model.generate(
            audio, 
            language = language, 
            extract_embedding = False
        )
    except Exception as e:
        logger.error(msg = f"Error during emotio2vec inference : {str(e)}")
        
    return np.array(result[0]['scores'], dtype = float)

def processScores(scores : np.ndarray) -> str:
    """ Extract emotion through scores returned by emotion2vec, merging neutral and other as a single category

    Args:
        scores (np.ndarray): scores generated by audio2emotion
    
    Returns:
        str : emotion label
    """

    # Labels from emotion2vec without unk and other
    labels = ['angry', 'disgusted', 'fearful', 'happy', 'sad', 'surprised', 'neutral']
    # Concatenate neutral, other and unk scores into a single column
    neutral = scores[4] + scores[5] + scores[8]
    scores = np.delete(scores, [4, 5, 8])
    scores = np.append(scores, [neutral])

    # Find the label corresponding to the maximum score
    max_index = np.argmax(scores)
    max_label = labels[max_index]
    return max_label