[tool.poetry]
name = "ubuntuserver"
version = "0.1.0"
description = ""
authors = ["Ifigeneia Manolou <ipm33@bath.ac.uk>"]
packages = [
    { include = "server", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.11, < 3.12"
fastapi = ">=0.139.2,<0.140.0"
orpheus-speech = "^0.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
